### ISSUE TITLE
aplt_scenario throws Twisted error

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/ap-loadtester#40]
aplt_scenario wss://autopush.stage.mozaws.net/ aplt.scenarios:basic

see:
https://pastebin.mozilla.org/8864659

note:
aplt_testplan is OK.

**Comment by rpappalax** [comment]
yes, this still persists:
https://pastebin.mozilla.org/

**Comment by pjenvey** [comment]
The pastebin links are now dead

**Comment by rpappalax** [comment]
can't repro, working now
