### ISSUE TITLE
Create "spawn all" scenarios to simplify API verification, loadtesting

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/ap-loadtester#48]
We need to have a way to spawn all the scenarios at once (with desired params) for these situations:
[1]. API verification 
 - aka: run all scenarios once, then stop
 - def _api_test()

[2]. loadtest 
- aka: run all scenarios continuously to generate load
- def _loadtest()

Per benbangert, we can create 2 additional 'wrapper' scenarios that spawn the others with the desired input params:
https://github.com/mozilla-services/ap-loadtester/blob/master/SCENARIOS.md#spawn

**Comment by rpappalax** [comment]
@benbangert 
I tried setting up a function like: https://github.com/mozilla-services/ap-loadtester/blob/master/aplt/scenarios.py#L122-L123
Individual yield statements execute successfully, but if i add in additional ones, I get a traceback:
exceptions.AttributeError: 'NoneType' object has no attribute 'handle'
Do i need to setup a runner to do multiple (back-to-back) yields within one function?

**Comment by bbangert** [comment]
Blocked on #41.
