### ISSUE TITLE
Add notification_forever_with_vapid scenario

### ISSUE THREAD

**Issue by rpappalax** [mozilla-services/ap-loadtester#77]
VAPID support was added to ap-loadtester, but we still need a scenario to test this.

from the README:
send_notification
Send a notification to the push service. If an empty data payload is desired, None can be used for data. If VAPID headers are desired, include a valid claims dict.

**Comment by jrconlin** [comment]
Has this been resolved? I believe I remember seeing a scenario regarding this.

**Comment by jrconlin** [comment]
Is this still valid? Is it still needed.

**Comment by rpappalax** [comment]
@jrconlin yes, it is still needed.

**Comment by pjenvey** [comment]
You can specify enabling of vapid headers on any scenario with these obscure arguments, e.g.:

aplt_testplan ws://localhost/ 'aplt.scenarios:notification_forever,10,1,0,{"vapid_claims":{"aud":"https://example.com"\,"sub":"mailto:admin@example.com"}}'

("exp" can also be included in the jwt dict: omitting it uses the current time + 24 hours)

**Comment by pjenvey** [comment]
Passing that through JSON for ardere's even more annoying, but doable, here's an example:

```
"steps": [
    {
      "name": "notification-forever-vapid",
      "cmd": "./apenv/bin/aplt_testplan ws://server/ 'aplt.scenarios:notification_forever,1000,1,0,{\"vapid_claims\":{\"aud\":\"https://example.com\"\\,\"sub\":\"mailto:admin@example.com\"}}'",
      "container_name": "bbangert/ap-loadtester:latest",
      "instance_count": 20,
      "instance_type": "m3.medium",
      "run_delay": 0,
      "run_max_time": 21600
    }
  ]
```

**Comment by rpappalax** [comment]
@pjenvey and i assume you also still need to specify:  --endpoint as below....

```
      "cmd": "./apenv/bin/aplt_testplan ws://autopush.stage.mozaws.net 'aplt.scenarios:notification_forever,100000,1,0,{\"vapid_claims\":{\"aud\":\"https://example.com\"\\,\"sub\":\"mailto:squirrel@example.com\"}}' --endpoint https://updates-autopush.stage.mozaws.net",
```

**Comment by rpappalax** [comment]
since this can be achieved as a cmd arg, closing this issue for creating a separate scenario
